//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AT_ASP.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autor_Livro
    {
        public int Id { get; set; }
        public int Id_Livro { get; set; }
        public int Id_Autor { get; set; }
    
        public virtual Autores Autores { get; set; }
        public virtual Livros Livros { get; set; }
    }
}
